eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/
  instance:
    prefer-ip-address: true #使用ip注册到eureka服务列表
server:
  port: 2000
spring:
  application:
    name: plat-service
